on:
  push:
    branches:
      - main
    # Pattern matched against refs/tags
    tags:
      - "*" # Push events to every tag not containing
  pull_request:

jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Hub
        uses: docker/login-action@v3
        with:
          registry: wert2all.nsupdate.info:5000
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: wert2all.nsupdate.info:5000/timeline/timeline-backend:latest
