name: EntCI
on:
  push:
    branches:
      - master
      - main
  pull_request:
    paths:
      - "ent/*"
jobs:
  ent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - uses: ent/contrib/ci@master
